//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Gestion_Commerciale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Contact = new HashSet<Contact>();
        }
    
        public short idClient { get; set; }
        public string raisonSociale { get; set; }
        public string typeSociete { get; set; }
        public string activite { get; set; }
        public string adresse { get; set; }
        public string complementAdresse { get; set; }
        public string villeClient { get; set; }
        public int codePostale { get; set; }
        public int telephone { get; set; }
        public string commentaires { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contact> Contact { get; set; }
    }
}
