//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Active_Gestion_Commerciale
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public short idContact { get; set; }
        public short idClient { get; set; }
        public string nomContact { get; set; }
        public string prenomContact { get; set; }
        public string telContact { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
